Provide `Base.oneunit()`
```
julia> euclidean(a, b)
ERROR: MethodError: no method matching VariableRef(::AffExpr)

Closest candidates are:
  (::Type{GenericVariableRef{T}} where T)(::Any, ::Any)
   @ JuMP ~/.julia/packages/JuMP/h0lrf/src/variables.jl:251
  GenericVariableRef{T}(::ConstraintRef{GenericModel{T}, <:MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex}}) where T
   @ JuMP ~/.julia/packages/JuMP/h0lrf/src/variables.jl:520
  GenericVariableRef{T}(::GenericModel{T}) where T
   @ JuMP ~/.julia/packages/JuMP/h0lrf/src/variables.jl:494

Stacktrace:
 [1] oneunit(#unused#::Type{VariableRef})
   @ Base ./number.jl:370
 [2] _eval_start(d::Euclidean, #unused#::Type{VariableRef}, #unused#::Type{VariableRef}, #unused#::Nothing)
   @ Distances ~/.julia/packages/Distances/PvoXa/src/metrics.jl:320
 [3] _eval_start(d::Euclidean, #unused#::Type{VariableRef}, #unused#::Type{VariableRef})
   @ Distances ~/.julia/packages/Distances/PvoXa/src/metrics.jl:318
 [4] eval_start(d::Euclidean, a::VariableRef, b::VariableRef)
   @ Distances ~/.julia/packages/Distances/PvoXa/src/metrics.jl:317
 [5] _evaluate(d::Euclidean, a::VariableRef, b::VariableRef, #unused#::Nothing)
   @ Distances ~/.julia/packages/Distances/PvoXa/src/metrics.jl:236
 [6] (::Euclidean)(a::VariableRef, b::VariableRef)
   @ Distances ~/.julia/packages/Distances/PvoXa/src/metrics.jl:328
 [7] top-level scope
   @ REPL[8]:1

```