Fix printing of models with large integers
Consider:
```
using JuMP, Ipopt
opt_model = Model(Ipopt.Optimizer, add_bridges = false)
@variable(opt_model, p)
@constraint(opt_model, p * 1e20 == 42)
print(opt_model)
```
```
InexactError: trunc(Int64, 1.0e20)

Stacktrace:
  [1] trunc
    @ ./float.jl:893 [inlined]
  [2] round
    @ ./float.jl:384 [inlined]
  [3] _string_round
    @ ~/.julia/packages/JuMP/jZvaU/src/print.jl:75 [inlined]
```

This did come up in an non-artificial situation.

In general, FP->Int cast, where the source FP value
is larger than the largest integer of the target type
is UB, and julia rightfully notices that.

Tests seem to suggest that edge cases at least don't cause UB.